language: python

python:
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.3"
  - "3.4"
  - "3.5"

install:
   - pip install coveralls

script:
   - python setup.py install
   - coverage run --source ytrans setup.py test

after_success:
   coveralls

